---

# Nginx
NGINX_ENABLE_SSL: False
NGINX_REDIRECT_TO_HTTPS: False

# Custom nginx var
nginx_mibank_gunicorn_hosts:
  - 127.0.0.1

MIBANK_DATABASE_NAME: "mibankapp"
MIBANK_DATABASE_USER: "mibank"
MIBANK_DATABASE_PASSWORD: "mibankpassword"

# Vars for postgresql role

postgresql_databases:
  - name: "{{ MIBANK_DATABASE_NAME }}"

postgresql_users:
  - name: "{{ MIBANK_DATABASE_USER }}"
    password: "{{ MIBANK_DATABASE_PASSWORD }}"
    db: "{{ MIBANK_DATABASE_NAME }}"
    priv: ALL
    role_attr_flags: NOSUPERUSER,NOCREATEDB
