---

- name: Bootstrap instances
  hosts: all
  gather_facts: no
  become: true
  roles:
    - python

- name: Provision mibank server
  hosts: app_servers
  gather_facts: yes
  become: true
  roles:
    - role: nginx
      nginx_extra_configs:
        - "files/nginx/mibank.j2"
    - role: geerlingguy.postgresql
    - role: mibank_service
